# config_train.yaml
# 用于在2020-2022年的数据上进行离线预训练

data:
  provider_uri: "~/.qlib/qlib_data/cn_data"
  start_date: "2020-01-01"
  end_date: "2022-12-31"
  universe: "csi300"

agent:
  learning_rate: 3.0e-4
  cvar_threshold: -0.015  # 优化CVaR约束
  cvar_lambda: 0.5      # 大幅增加CVaR权重
  hidden_dim: 256         # 增加网络容量

risk_control:
  target_volatility: 0.10 # 降低目标波动率
  max_leverage: 1.2       # 降低杠杆

environment:
    max_leverage: 1.2 # 降低环境杠杆

safety_shield:
    max_leverage: 1.2 # 降低安全保护层杠杆

training:
  total_episodes: 1000 # 增加训练回合数

factors:
  low_vol_threshold: 0.2 # 降低波动率阈值

model:
  save_dir: "./models/csi300_2020_2022"

o2o: {}
