# config_backtest.yaml
# 用于在2023年的全新数据上回测模型

data:
  provider_uri: "~/.qlib/qlib_data/cn_data"
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  universe: "csi300"

# 回测时不需要训练和agent配置，但需要risk_control来管理风险
# 使用优化后的风险控制参数
risk_control:
  target_volatility: 0.15  # 提升目标波动率以匹配收益目标
  max_leverage: 1.4         # 提升杠杆倍数
