# Prometheus配置文件
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 交易系统监控
  - job_name: 'rl-trading-system'
    static_configs:
      - targets: ['rl-trading-system:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # InfluxDB监控
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']