description: 平衡性能与资源消耗，推荐用于大部分场景
name: 标准配置
sac:
  action_dim: 3
  hidden_dim: 512
  state_dim: 256
  use_transformer: true
transformer:
  activation: gelu
  d_ff: 1024
  d_model: 256
  dropout: 0.1
  max_seq_len: 252
  n_features: 37
  n_heads: 8
  n_layers: 6
