# 监控配置文件
monitoring:
  prometheus:
    port: 8000
    metrics_path: "/metrics"
    
  thresholds:
    max_drawdown: 0.15
    min_sharpe_ratio: 0.5
    max_var_95: 0.03
    lookback_days: 90
    
  alerts:
    channels:
      - email
      - dingtalk
    email:
      smtp_server: "smtp.gmail.com"
      smtp_port: 587
      username: ""
      password: ""
      recipients: []
    dingtalk:
      webhook_url: ""
      
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
  rotation: "1 day"
  retention: "30 days"
  compression: "gz"