# 交易配置文件
# 支持环境变量覆盖，例如：TRADING_ENVIRONMENT_INITIAL_CASH=2000000.0
trading:
  environment:
    # 股票池，将在运行时填充，可通过 TRADING_ENVIRONMENT_STOCK_POOL 覆盖
    stock_pool:
      - "601288.SH"  # 农业银行
      - "600036.SH"  # 招商银行
      - "600919.SH"  # 中国平安
    lookback_window: 60         # 回看窗口，可通过 TRADING_ENVIRONMENT_LOOKBACK_WINDOW 覆盖
    initial_cash: 1000000.0     # 初始资金，可通过 TRADING_ENVIRONMENT_INITIAL_CASH 覆盖
    commission_rate: 0.0005     # 手续费率 0.05%，可通过 TRADING_ENVIRONMENT_COMMISSION_RATE 覆盖
    stamp_tax_rate: 0.0005      # 印花税率 0.05%，可通过 TRADING_ENVIRONMENT_STAMP_TAX_RATE 覆盖
    risk_aversion: 0.01         # 风险厌恶系数（降低以减少过度惩罚），可通过 TRADING_ENVIRONMENT_RISK_AVERSION 覆盖
    max_drawdown_penalty: 1.0   # 最大回撤惩罚，可通过 TRADING_ENVIRONMENT_MAX_DRAWDOWN_PENALTY 覆盖

  cost_model:
    almgren_chriss:
      permanent_impact: 0.1     # 永久冲击系数，可通过 TRADING_COST_MODEL_ALMGREN_CHRISS_PERMANENT_IMPACT 覆盖
      temporary_impact: 0.05    # 临时冲击系数，可通过 TRADING_COST_MODEL_ALMGREN_CHRISS_TEMPORARY_IMPACT 覆盖

  data:
    provider: "qlib"            # 数据提供商 qlib 或 akshare，可通过 TRADING_DATA_PROVIDER 覆盖
    cache_enabled: true         # 是否启用缓存，可通过 TRADING_DATA_CACHE_ENABLED 覆盖
    cache_dir: "./data_cache"   # 缓存目录，可通过 TRADING_DATA_CACHE_DIR 覆盖

# 回撤控制配置
drawdown_control:
  enable: true  # 启用回撤控制

  # 基础回撤参数
  max_drawdown_threshold: 0.10        # 最大回撤阈值 10%
  drawdown_warning_threshold: 0.05    # 回撤警告阈值 5%

  # 风险控制参数
  drawdown_penalty_factor: 3.0        # 回撤惩罚因子
  risk_aversion_coefficient: 0.8      # 风险厌恶系数

  # 市场状态感知
  enable_market_regime_detection: true  # 启用市场状态检测

  # 训练相关参数
  max_training_drawdown: 0.5           # 训练过程最大允许回撤（适应负奖励环境）
  enable_adaptive_learning: true      # 启用自适应学习

  # 自适应学习率参数
  lr_adaptation_factor: 0.9            # 学习率衰减因子（更温和）
  min_lr_factor: 0.01                  # 最小学习率因子
  max_lr_factor: 1.0                   # 最大学习率因子
  lr_recovery_factor: 1.25             # 学习率恢复因子
  performance_threshold_down: 0.85     # 性能下降阈值（更严格）
  performance_threshold_up: 1.15       # 性能提升阈值（更严格）

backtest:
  freq: "1d"                    # 回测频率 1d 或 1min，可通过 BACKTEST_FREQ 覆盖
  rebalance_freq: "1d"          # 再平衡频率，可通过 BACKTEST_REBALANCE_FREQ 覆盖
  start_date: "2024-01-01"      # 回测开始日期，可通过 BACKTEST_START_DATE 覆盖
  end_date: "2025-08-01"        # 回测结束日期，可通过 BACKTEST_END_DATE 覆盖
  benchmark: "000300.SH"        # 基准指数（沪深300），可通过 BACKTEST_BENCHMARK 覆盖

# 增强指标配置
enhanced_metrics:
  enable_portfolio_metrics: true          # 启用投资组合指标（夏普比率、最大回撤、Alpha、Beta等）
  enable_agent_behavior_metrics: true     # 启用智能体行为指标（熵、持仓集中度、换手率等）
  enable_risk_control_metrics: true       # 启用风险控制指标（风险预算使用情况等）
  metrics_calculation_frequency: 20       # 指标计算频率（每N个episode计算一次）
  detailed_metrics_logging: true          # 启用详细指标日志
  risk_free_rate: 0.03                    # 无风险利率（用于夏普比率等计算）

# 风险管理配置
risk:
  enable_risk_control: true
  max_portfolio_concentration: 0.4
  max_single_position: 0.15
  min_cash_ratio: 0.05%

# 模型配置
model:
  transformer:
    d_model: 128
    n_heads: 8
    n_layers: 4
    d_ff: 512
    dropout: 0.1
    max_seq_len: 60
    n_features: 37   # 每只股票的特征数（与已训练模型一致）

  # SAC 配置 - 基于 stable_baselines3
  sac:
    # 基础学习参数
    lr_actor: 0.0003                # Actor 学习率（兼容性保留）
    lr_critic: 0.0003               # Critic 学习率（兼容性保留）
    lr_alpha: 0.0003                # Alpha 学习率（兼容性保留）
    learning_rate: 0.0003           # SB3 统一学习率
    
    # SAC 算法参数
    gamma: 0.99                     # 折扣因子
    tau: 0.005                      # 软更新系数
    ent_coef: "auto"                # 熵系数，"auto" 表示自动调整
    target_entropy: "auto"          # 目标熵，"auto" 表示 -dim(action_space)
    
    # 训练参数
    batch_size: 256                 # 批次大小
    buffer_size: 100000             # 经验回放缓冲区大小
    learning_starts: 1000           # 开始学习的最小步数
    train_freq: 1                   # 训练频率
    gradient_steps: 1               # 每次更新的梯度步数
    target_update_interval: 1       # 目标网络更新间隔
    
    # 网络架构
    hidden_dim: 256                 # 隐藏层维度
    net_arch: [256, 256]           # 网络架构（两层 256 单元）
    activation_fn: "relu"           # 激活函数
    
    # 兼容性参数（用于旧配置）
    action_dim: 3                   # 动作维度（3只股票的权重）
    state_dim: 128                  # 状态维度（Transformer输出维度）
    
    # SB3 特定参数
    use_sde: false                  # 是否使用状态相关探索
    sde_sample_freq: -1             # SDE 采样频率
    use_sde_at_warmup: false        # 预热时是否使用 SDE

  training:
    # 训练轮数和评估
    n_episodes: 100                 # 训练轮数（用于计算总时间步数）
    total_timesteps: 25200          # 总训练时间步数 (100 episodes * 252 trading days)
    eval_freq: 5000                 # 评估频率
    n_eval_episodes: 10             # 评估时的回合数
    save_freq: 10000                # 模型保存频率
    
    # 早停参数
    patience: 20                    # 早停耐心
    min_delta: 0.001                # 最小改进阈值
    
    # SB3 训练参数
    verbose: 1                      # 详细程度
    device: "auto"                  # 设备选择："auto", "cpu", "cuda"
    
    # 多核优化配置（部分在 SB3 中不直接适用，保留用于环境并行）
    enable_multiprocessing: false   # SB3 内部处理并行，禁用外部多进程
    num_workers: 4                  # 环境工作进程数
    parallel_environments: 1       # 并行环境数量（SB3 使用 VecEnv）
    data_loader_workers: 2          # DataLoader工作线程数
    pin_memory: true                # GPU内存固定
    persistent_workers: false       # 持久化工作进程
    prefetch_factor: 2              # 预取因子
    
    # GPU优化配置
    enable_mixed_precision: false   # SB3 自动处理混合精度
    enable_cudnn_benchmark: true    # 启用cuDNN基准测试
    non_blocking_transfer: true     # 非阻塞数据传输
