# SAC算法分钟线数据配置文件
# 适用于高频交易策略，使用分钟线数据进行训练
# 基于fix.md分析报告的优化改进

# 数据配置
data:
  data_root: "/Users/shuzhenyi/.qlib/qlib_data"
  provider_uri:
    1min: "/Users/shuzhenyi/.qlib/qlib_data/cn_data_1min"
    day: "/Users/shuzhenyi/.qlib/qlib_data/cn_data"
  market: "csi300"
  stock_limit: 30  # 分钟线数据计算量大，减少股票数量
  # 可选：自定义股票池（如果指定则优先使用，否则使用market参数）
  custom_stocks: null  # 例: ["sh600000", "sz000001", "sh600036"]
  start_time: "2022-01-01"
  end_time: "2023-12-31"
  train_start: "2022-01-01"
  train_end: "2023-06-30"
  valid_start: "2023-07-01"
  valid_end: "2023-09-30"
  test_start: "2023-10-01"
  test_end: "2023-12-31"
  freq: "1min"
  fields:
    - "$close"
    - "$open"
    - "$high"
    - "$low"
    - "$volume"
    - "$vwap"

# 环境配置
environment:
  initial_cash: 1000000
  lookback_window: 60  # 1小时历史窗口
  transaction_cost: 0.005  # 分钟线交易成本稍高
  max_drawdown_threshold: 0.08  # 更严格的回撤控制（分钟线更严格）
  reward_penalty: 5.0  # 增强回撤惩罚力度
  features:
    - "$close"
    - "$open"
    - "$high"
    - "$low"
    - "$volume"
    - "$vwap"
  rebalance_freq: "1min"
  max_steps: 240  # 确保episode足够长（对分钟线约240分钟）

# 模型配置
model:
  algorithm: "SAC"
  learning_rate: 0.003  # 提高学习率以适应新的奖励尺度
  batch_size: 512
  gamma: 0.995  # 更重视长期奖励
  buffer_size: 2000000  # 更大的经验回放缓存
  tau: 0.001  # 更慢的目标网络更新
  target_update_interval: 2
  learning_starts: 1000
  use_custom_policy: true
  net_arch:
    - 512
    - 256
    - 128

# 训练配置
training:
  total_timesteps: 2000000  # 分钟线需要更多训练步数
  n_envs: 6  # 并行环境数
  seed: 2024
  log_interval: 20

# 回调配置
callbacks:
  enable_eval: true
  eval_freq: 20000
  n_eval_episodes: 3
  enable_checkpoint: true
  save_freq: 100000
  enable_drawdown_stopping: true
  max_training_drawdown: 0.08      # 更严格的回撤阈值
  drawdown_patience: 20            # 更快的早停响应
  enable_tensorboard: true
  enable_training_metrics: true     # 启用训练指标监控
  metrics_log_interval: 2000       # 每2000步输出基础指标
  metrics_eval_interval: 10000     # 更频繁的详细评估

# 评估配置
evaluation:
  n_episodes: 10

# 日志配置
log_level: "INFO"

# 风险控制
risk_control:
  max_position_ratio: 0.2  # 单只股票最大仓位
  stop_loss_ratio: 0.05    # 止损比例
  take_profit_ratio: 0.10  # 止盈比例
  volatility_limit: 0.04   # 波动率限制