# O2O平衡策略配置模板
# 适用于风险收益平衡的量化交易场景

data:
  start_date: '2020-01-01'
  end_date: '2023-12-31'
  universe: 'csi300'
  factors: ['technical', 'fundamental']
  apply_cleaning: true
  outlier_threshold: 3.0

o2o:
  # 离线预训练参数 - 平衡设置
  offline_epochs: 100
  behavior_cloning_weight: 0.5
  td_learning_weight: 0.5
  offline_batch_size: 256
  offline_lr: 3e-4
  
  # 热身微调参数 - 平衡设置
  warmup_days: 60
  warmup_epochs: 20
  critic_only_updates: true
  warmup_lr: 1e-4
  convergence_threshold: 0.01
  
  # 在线学习参数 - 平衡设置
  initial_rho: 0.2
  rho_increment: 0.01
  trust_region_beta: 1.0
  beta_decay: 0.99
  online_buffer_size: 10000
  priority_alpha: 0.6
  priority_beta: 0.4
  importance_weight_clip: 10.0
  
  # 漂移检测参数 - 标准设置
  kl_threshold: 0.1
  sharpe_drop_threshold: 0.2
  cvar_breach_threshold: -0.02
  drift_window: 30
  noise_filter: true

agent:
  hidden_dims: [256, 128, 64]
  activation: 'relu'
  cvar_alpha: 0.05
  risk_lambda: 1.0
  entropy_coef: 0.01
  value_coef: 0.5
  max_grad_norm: 0.5

environment:
  initial_capital: 1000000
  transaction_cost: 0.001
  max_position: 0.1
  rebalance_freq: 'daily'
  risk_free_rate: 0.03

training:
  max_episodes: 1000
  eval_freq: 50
  save_freq: 100
  early_stopping_patience: 200

logging:
  level: 'INFO'
  save_logs: true
  log_dir: 'logs/balanced'
  tensorboard: true
  detailed_metrics: true